# Generated by Django 5.0.6 on 2026-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='route_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
