# Generated by Django 5.0.6 on 2026-05-21 01:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0002_workoutsession_route_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('target_sets', models.PositiveSmallIntegerField(default=3)),
                ('target_reps', models.CharField(default='', help_text="Notação livre: '10', '8-12', 'AMRAP', '30s', etc.", max_length=20)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exercises.exercise')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workouttemplate')),
            ],
            options={
                'verbose_name': 'Template Exercise',
                'verbose_name_plural': 'Template Exercises',
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
    ]
