# Generated by Django 5.0.6 on 2026-05-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_scheduledworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlog',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
